from django.shortcuts import render, redirect
from django.contrib import messages
from .models import *
import bcrypt

# render home page
def index(request):
    return render(request, "index.html")

#process registration and redirect
def register(request):
    errors = User.objects.register(request.POST)
    if len(errors) > 0:
        for key,error in errors.items():
            messages.error(request, error)
        return redirect("/")
    else:
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt()).decode()
        user = User.objects.create(email=request.POST['email'].lower(), password=pw_hash, first_name=request.POST['first_name'], last_name=request.POST['last_name'],birthday=request.POST['birthday'])
        request.session['user_id'] = user.id #generated by django
        request.session['first_name'] = user.first_name
        request.session['last_name'] = user.last_name
        messages.success(request, "Registered successfully :)")
        return redirect("/")    

# process login info and redirect
def login(request):
    errors = User.objects.login(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error)
        return redirect("/")
    else:
        user = User.objects.filter(email=request.POST['email'].lower())
        if len(user) < 1:
            messages.error(request, "No User for that email")
            return redirect("/signin")
        
        if bcrypt.checkpw(request.POST['password'].encode(), user[0].password.encode()):
            print(f"LOG - Setting session value 'user_id' = {user[0].id}")
            request.session['user_id'] = user[0].id
            request.session['first_name'] = user[0].first_name
            return redirect("/")
        else:
            messages.error(request, "Incorrect Password!")
            return redirect("/signin")

# logout and redirect
def logout(request):
    request.session.clear()
    messages.success(request, "Log out successful!")
    print(f"LOG - Log out successful, redirecting to home")  
    return redirect("/signin")

# render success page
def wall(request):
    if 'user_id' not in request.session:
        messages.error(request, "Login first")
        return redirect("/signin")
    context = {
        "user_id" : request.session['user_id'],
        "posts": Messages.objects.all().order_by("-created_at"),
        "comments": Comments.objects.all()      
    }
    return render(request,'home.html', context)
    

def message(request):
    user = User.objects.get(id= request.session['user_id'])
    post = Messages.objects.create(user_id=user,message=request.POST['message'])
    return redirect('/')

def comment(request):
    user = User.objects.get(id= request.session['user_id'])
    message = Messages.objects.get(id=request.POST['message_id'])
    Comments.objects.create(message_id=message,user_id=user,comment=request.POST['comment'])
    return redirect('/')